---
stages:
- name: Deploy App
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Push to Bluemix
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |
      cf push "${CF_APP}" 
      cf map-route "${CF_APP}" mybluemix.net -n "${CF_APP}"-pm 
- name: Deploy Arc
  inputs:
  - type: git
    branch: master
  triggers:
    - type: stage
  jobs:
  - name: Push Arc to Bluemix
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |
      cd .bluemix
      cf push "${CF_APP}"  -n "${CF_APP}"-arc      